### ISSUE TITLE
Some symbol is invisible in light color scheme

### ISSUE THREAD

**Issue by Enter-tainer** [supersurviveur/typst-math#1]
I just tried this extension and it is really cool! One thing I noticed is that the default color scheme may not suitable for light color scheme.

<img width="297" alt="image" src="https://github.com/supersurviveur/typst-math/assets/25521218/42ad065f-45c4-4df8-a468-b4813f7deee1">
<img width="391" alt="image" src="https://github.com/supersurviveur/typst-math/assets/25521218/050256bc-7ee6-4d21-9551-b9909fe21e22">

**Comment by supersurviveur** [comment]
Thanks !
Using the theme colors is unfortunately impossible, because of the [extension API](https://github.com/microsoft/vscode/issues/32813).

I'm going to try setting different default colours for light and dark themes, instead of just using the monokai theme colors.

**Comment by Enter-tainer** [comment]
thank you for quick reply! it will be nice to have a color scheme for light theme🥰👍

**Comment by supersurviveur** [comment]
Closed too early, default light theme colors will be available in the version `v0.0.4`

**Comment by supersurviveur** [comment]
Fixed in `v0.0.4`
If you find that default light colors are not adapted or not readable, feels free to reopen the issue and offer other colors.
