### ISSUE TITLE
problème d'affichage pour diaer

### ISSUE THREAD

**Issue by Le-foucheur** [supersurviveur/typst-math#11]
quand on utilise la fonction diaer pour mettre deux points au dessus d'une variable ceci ce mettent sur le coté gauche au lieux de sus et ne retire pas les parenthèse dû à la fonction (cf: les images) 

le code en luis même 
<img width="89" alt="Capture d’écran 2024-04-14 à 17 18 37" src="https://github.com/supersurviveur/typst-math/assets/38878602/36cce249-470e-4659-b165-0ff92bcb3830">

ce que l'extension affiche: 
<img width="64" alt="Capture d’écran 2024-04-14 à 17 16 56" src="https://github.com/supersurviveur/typst-math/assets/38878602/2151ed0f-b1af-4ad6-99cb-860dc390fe39">

ce qui est attendu
<img width="26" alt="Capture d’écran 2024-04-14 à 17 17 21" src="https://github.com/supersurviveur/typst-math/assets/38878602/7786f38c-16c2-4bf1-945e-40686fe4821d">

**Comment by supersurviveur** [comment]
Problem fixed in `v0.0.12`
