### ISSUE TITLE
adding typst-math to open-vsx registry

### ISSUE THREAD

**Issue by beling** [supersurviveur/typst-math#2]
Hello,

Thank you for developing such a wonderful and needed extension.

At the same time, to make VSCodium users happy, I suggest adding it to the open-vsx registry:
https://open-vsx.org/

Kind regards
Piotr Beling

**Comment by supersurviveur** [comment]
Hi,
Thanks for your suggestion !
I published the version `v0.0.4` on [open-vsx](https://open-vsx.org/extension/surv/typst-math).
However, I can't currently check that the extension on open-vsx works fine.

**Comment by supersurviveur** [comment]
It seems to work fine.
I close this issue.
Thanks !
