### ISSUE TITLE
Wrong rendering about divergence symbol with physica package

### ISSUE THREAD

**Issue by enYao39** [supersurviveur/typst-math#20]
When I type ‘div’, it renders as a division symbol rather than a divergence symbol.
![image](https://github.com/supersurviveur/typst-math/assets/128119128/73925263-197c-46ad-a088-1ede51098a4f)
Actuall it should be 
![image](https://github.com/supersurviveur/typst-math/assets/128119128/dd0a6150-4b14-423f-a188-c2cda2dd3045)

**Comment by enYao39** [comment]
And it seems that symbols from the package `@preview/physica:0.9.0` are not supported.
When i type `curl` it should be 
![image](https://github.com/supersurviveur/typst-math/assets/128119128/09c92358-3953-4ff4-843f-3cda0f165b6e)
but it just stays as 
![image](https://github.com/supersurviveur/typst-math/assets/128119128/1f38e9c1-be31-4246-b244-c44448fc3a7c)

**Comment by supersurviveur** [comment]
Hi !
I just checked the typst website, and `div` symbol is the division symbol.
https://typst.app/docs/reference/symbols/sym/

I think your symbol is `nabla`

**Comment by supersurviveur** [comment]
Oh, physica overrides some symbols like `div`.
I don't know if support physica is possible if they use their own symbols.
Maybe we can create a setting to select some packages, but seems complicated for just few symbols.

**Comment by supersurviveur** [comment]
Phisyca gives a list of symbols here  https://github.com/Leedehai/typst-physics/blob/master/physica-manual.pdf

**Comment by supersurviveur** [comment]
I just added three symbols `grad`, `curl`, and `div` with a setting.
Other changes seems to be functions, so i won't render them.
Tell me if I'm wrong

**Comment by enYao39** [comment]
Thanks，that's helpful 😊

**Comment by supersurviveur** [comment]
Nevermind, I changed my approach.
Now you can define custom symbols in the settings, and override default ones.
In your case you can use something like : 
```json
    "typst-math.customSymbols": [
        {
            "name": "div",
            "symbol": "∇",
            "category": "operator"
        }
    ]
```
in `settings.json`

**Comment by supersurviveur** [comment]
Added in `v0.1.1`
