### ISSUE TITLE
Command to replace symbols with unicode characters

### ISSUE THREAD

**Issue by Atreyu-94** [supersurviveur/typst-math#21]
Sometimes I find it useful to write the math in unicode format and would rather have the unicode symbol in the equation than its specific name.

This also happens to me with the mathematical typeface, sometimes you want to write a word in $ cal(ABC) $ and that within the equation there is simply ABC with the style "cal". The JuliaMono typeface supports all of these symbols in the editor:P . 

Would this be possible? Could it be done on files that aren't just typst?

**Comment by supersurviveur** [comment]
I don't understand what you mean, `$ cal(ABC) $` is already rendered with unicode symbols.

**Comment by Atreyu-94** [comment]
I'm sorry if I didn't explain myself well. What I would like is for there to be an option for the code to be replaced with its unicode symbol, for example by entering `$ cal(ABC) $` get in the editor (not only in the render) `$ 𝒜ℬ𝒞 $`. Another example, when you put in `$ integral $` get `$ 
∫ $`. That is, instead of having the names of the symbols, they are replaced by unicode symbols.

**Comment by supersurviveur** [comment]
Oh, I understand. It seems hard to implement but sounds like a great idea. However it's hard to tell which symbols have to be converted and I don't know if it's something useful for a lot of people. Tbh I don't have the time to implement something like that for the moment, but feel free to contribute !
