### ISSUE TITLE
Automatically Remove Unnecessary Parentheses

### ISSUE THREAD

**Issue by yama662607** [supersurviveur/typst-math#27]
Could you add a feature to automatically remove unnecessary parentheses when rendering?

For example,
```
f(x, y)
(a b c)^2
(a/b)/c
```
 cannot be simplified as removing the parentheses would change the meaning.

However, for expressions like
```
e^(2 x y)
(d y)/(d x)a b
integral_(pi/2)^(2pi)
```
the parentheses can be omitted and the spaces between variables can be condensed, rendering as:
```
e^2xy (where 2, x, y are rendered as subscripts)
dy/dx ab
integral_pi/2^2pi (where pi, /, 2 are rendered as subscripts, and 2, pi are rendered as superscripts)
```
Thank you for considering this request.

**Comment by supersurviveur** [comment]
Hi ! Thanks for your issue.
A setting will be able in the next version to hide these unnecessary delimiters, set to `false` by default.

**Comment by yama662607** [comment]
Thank you so mach!
I'm looking forward to the update.
