### ISSUE TITLE
Error in Syntax highlight

### ISSUE THREAD

**Issue by yama662607** [supersurviveur/typst-math#28]
I have noticed that even when setting the syntax color for typst-math to white, there are instances where the color is influenced by the surrounding symbols, causing it to appear colored.
<img width="808" alt="スクリーンショット 2024-06-06 15 52 10" src="https://github.com/supersurviveur/typst-math/assets/124486175/ef77fac1-4c3f-49a7-b635-6802df9cf6ca">

extension OFF
<img width="1291" alt="スクリーンショット 2024-06-06 16 06 13" src="https://github.com/supersurviveur/typst-math/assets/124486175/343f29fc-cfc8-4d14-94c1-3634cadc7f0a">

extension ON
<img width="937" alt="スクリーンショット 2024-06-06 16 05 45" src="https://github.com/supersurviveur/typst-math/assets/124486175/4adb6739-1912-487b-a238-3ca897286e5b">

**Comment by supersurviveur** [comment]
Thanks for your contribution.
It seems that it comes from the color code, you must use the # before the code (`#ffffff`). It allows user to use RGB colors, but
I will add it in the documentation or/and add a check if possible.

**Comment by yama662607** [comment]
Oops, I've made a simple mistake.
Syntax highlighting works well after adding the `#` to the code. Thank you for your advice.
