### ISSUE TITLE
Prompt to install fonts leads to a 404 page

### ISSUE THREAD

**Issue by NicoWeio** [supersurviveur/typst-math#29]
This link doesn't work:
https://github.com/supersurviveur/typst-math/blob/main/fonts/

And here's the code that seems to trigger the prompt:
https://github.com/supersurviveur/typst-math/blob/9101f0f9ca6c6c5d49c32ac8a29e90f65c84663f/src/commands/installFonts.ts#L5

I didn't do any further research.

**Comment by supersurviveur** [comment]
Thanks for your contribution. Fixed in `v0.1.5`
