### ISSUE TITLE
Clicked automatically install fonts on MacOS and now Typst doesn't render math anymore

### ISSUE THREAD

**Issue by ChHecker** [supersurviveur/typst-math#3]
I downloaded the extension in VSCode and clicked on `automatically install fonts` without knowing it only works on Windows. I am on MacOS. Now, Typst doesn't render math anymore.
1. Where is it installed so I can remove it?
2. Users shouldn't be prompted on other systems if it doesn't work.

**Comment by supersurviveur** [comment]
Hi !
Sorry for the disagreement.

1 - Normally fonts are installed in the font directory of macos, but on Mac and Linux, it just doesn't work I think.
2 - You are right, I will try to improve the system

Can you send a screenshot of the problem ?
You can also try to install the fonts manually.

**Comment by supersurviveur** [comment]
In `v0.0.6`, `install with bundled program` button is only shown on windows.

**Comment by supersurviveur** [comment]
Tested on a mac, the button is only shown on windows. It seems that installing fonts automatically on other system is nearly impossible, so i close this issue.
