### ISSUE TITLE
Square Root symbol broken

### ISSUE THREAD

**Issue by RedViperPT** [supersurviveur/typst-math#7]
The square root symbol only renders on some equations and it seems a bit broken when it does render.

![Screenshot_20240304_214841](https://github.com/supersurviveur/typst-math/assets/40699748/22e5ad3e-bb67-44fe-877c-5d2609d8d1c5)

This happens on both my linux and windows machines

**Comment by supersurviveur** [comment]
Hi,
I think that I forgot to set the font of the upper character, so the size and position change if you don't have the same font for default text in VSCode. I will force to use a font installed with the extension.
For the second equation, this is normal, my extension only renders basic symbols/equations, I can try to render more complexe things, but it's hard to find a simple/optimised way to render a lot of symbols without too many conditions and special cases.

**Comment by RedViperPT** [comment]
Thanks for the quick bug fix!

 I can appreciate that it is hard to make this work on every case, I just wasn't sure if it was supposed to render or not in the second case.  

One further request I would make is to allow us to choose if a character gets rendered or not, I know we can choose between some presets but allowing us to pick specific exceptions would be great.  

Thanks again for your work.

**Comment by supersurviveur** [comment]
I will publish the modification in the next version, and put the vsix file here with the patch to allow you to download it before the next release.

I like your idea about choosing precisely symbols, I will also try to add it.

**Comment by supersurviveur** [comment]
Here is the vsix file with the patch.
[typst-math-0.0.8.zip](https://github.com/supersurviveur/typst-math/files/14499881/typst-math-0.0.8.zip)

Can you open another issue for the symbols rendering settings ? And one for more complexe rendering if you want too.
Thank you !
