### ISSUE TITLE
Feature Request — Symbol Blacklist

### ISSUE THREAD

**Issue by RedViperPT** [supersurviveur/typst-math#8]
As I said in the other issue, I think it would be useful if we could pick specific symbols to not be rendered by typst-math.

Maybe someone doesn't like how exponents get rendered, they become kinda tiny and it could decrease readability, whatever the reason, I think it would be useful.

**Comment by supersurviveur** [comment]
Hi !
In `v0.0.10`, a lot of text symbols can be blacklisted.
I will try to add options to blacklist missing symbols too.

**Comment by supersurviveur** [comment]
Symbols can completely be blacklisted with rendering mode and blacklist
Closed in `v0.1.0`
