### ISSUE TITLE
Typst LSP dependency

### ISSUE THREAD

**Issue by pride7** [supersurviveur/typst-math#9]
Is it possible to remove the dependency on typst lsp? I mean, I'm trying other lsp plugins (that have the same interface as typst lsp) but can't continue to use typst math due to its forced dependency on the typst lsp plugin.

**Comment by supersurviveur** [comment]
Hi !
It's a good idea, the dependency is not really needed.
I will remove it in the next version.

**Comment by supersurviveur** [comment]
Removed in `v0.0.10`
